### ISSUE TITLE
Singature

### ISSUE THREAD

**Issue by Deepaksaini2612** [fanerobinson/PSA#14]
Hi Husein,
could you please update my signature? Clients are not able to recognize who is sending an email to them. could you please do this asap  
![1](https://cloud.githubusercontent.com/assets/23490470/20589049/b45a049e-b254-11e6-9e0a-05e0bc96077c.PNG)

**Comment by huzzamo** [comment]
Updated signature. Can you check and advise if any changes?

(Leave the pipes in)
Deepak Saini|BSc Computer Science|Information Technology Specialist|BIZ-LYNX Technology Pty Ltd|(+618) 6263-9400|(+618) 6263-9420|team@biz-lynx.com.au

**Comment by Deepaksaini2612** [comment]
Could you please update as below.

Deepak Saini|B.Tech Computer Science, M.Tech Internetworking and Security|System Engineer|BIZ-LYNX Technology Pty Ltd|(+618) 6263-9400|(+618) 6263-9420|team@biz-lynx.com.au<mailto:team@biz-lynx.com.au>


[BIZ-LYNX Technology logo]

Deepak Saini

B.Tech Computer Science, M.Tech Internetworking and Security, CCNA Certified
System Engineer
BIZ-LYNX Technology Pty Ltd





Phone

(+618) 6263-9400

Fax

(+618) 6263-9420

Email

team@biz-lynx.com.au<mailto:team@biz-lynx.com.au>


www.biz-lynx.com.au <http://www.biz-lynx.com.au/>


Trading Hours

WST

09:00 - 17:00 Monday - Friday

EST

11:00 - 19:00 Monday - Friday

Other

By Appointment





P Please consider the environment before printing this email, be green, read from the screen!

**Comment by huzzamo** [comment]
Done.

________________________________

**Comment by Deepaksaini2612** [comment]
Husein could you please see this below [cid:image001.png@01D24A59.4CFC17A0]

This is what it looks like when I open the ticket and could you please amend my signature like this sorry for being a pain
Deepak Saini|B.Tech Computer Science, M.Tech Internetworking and Security, CCNA Certified|System Engineer|BIZ-LYNX Technology Pty Ltd|(+618) 6263-9400|(+618) 6263-9420|team@biz-lynx.com.au<mailto:team@biz-lynx.com.au<mailto:6263-9420|team@biz-lynx.com.au%3cmailto:team@biz-lynx.com.au>>


[BIZ-LYNX Technology logo]

Deepak Saini

B.Tech Computer Science, M.Tech Internetworking and Security, CCNA Certified
System Engineer
BIZ-LYNX Technology Pty Ltd





Phone

(+618) 6263-9400

Fax

(+618) 6263-9420

Email

team@biz-lynx.com.au<mailto:team@biz-lynx.com.au>


www.biz-lynx.com.au <http://www.biz-lynx.com.au/>


Trading Hours

WST

09:00 - 17:00 Monday - Friday

EST

11:00 - 19:00 Monday - Friday

Other

By Appointment





P Please consider the environment before printing this email, be green, read from the screen!
