### ISSUE TITLE
font for emails + signature

### ISSUE THREAD

**Issue by fanerobinson** [fanerobinson/PSA#2]
signature and email body not carrying across fonts from editor

example current result email regardless of font selected
![image](https://cloud.githubusercontent.com/assets/23490104/20331816/d28ea55a-abe2-11e6-96b7-a8dbb6315efc.png)

proper signature
![image](https://cloud.githubusercontent.com/assets/23490104/20331794/bb8b2ed2-abe2-11e6-9586-989d6f3a444b.png)

**Comment by fanerobinson** [comment]
Updated view of outgoing messages.

![image](https://cloud.githubusercontent.com/assets/23490104/20475488/256958f6-b007-11e6-8855-da39c5ff4101.png)

**Comment by fanerobinson** [comment]
![image](https://cloud.githubusercontent.com/assets/23490104/20475887/008983ec-b009-11e6-8411-42ad6c85f268.png)

**Comment by huzzamo** [comment]
Have cleaned-out your signature. Let me know how you go. Will add some major updates later this week.

**Comment by fanerobinson** [comment]
currently no signature at all? they dont know who is emailing them except for the logo

![image](https://cloud.githubusercontent.com/assets/23490104/20511052/f3233070-b0af-11e6-8542-6a36ed8932d6.png)

**Comment by huzzamo** [comment]
Added temp signature.
