### ISSUE TITLE
cannot update time on email ticket

### ISSUE THREAD

**Issue by fanerobinson** [fanerobinson/PSA#4]
i change start time and finish time, click the time icon to get it to calculate it correctly and then click update but it doesnt update

**Comment by fanerobinson** [comment]
this doesnt work for closure either

**Comment by huzzamo** [comment]
There are 2 methods to change time:
- Manually by changing start and end time
- Clicking on create and update time button

Which one is not working? Can you send a screenshot of this?

**Comment by fanerobinson** [comment]
changing start time doesnt work

**Comment by fanerobinson** [comment]
![image](https://cloud.githubusercontent.com/assets/23490104/20655492/efaa98a4-b55d-11e6-9e95-3266dd9b7117.png)

thinks is after the start time but it isnt

**Comment by fanerobinson** [comment]
doesn't work if you put 09:00 either

**Comment by huzzamo** [comment]
Can you try 9a

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Nov 28, 2016 at 11:30 AM +0800, "fanerobinson" <notifications@github.com<mailto:notifications@github.com>> wrote:


[image]<https://cloud.githubusercontent.com/assets/23490104/20655492/efaa98a4-b55d-11e6-9e95-3266dd9b7117.png>

thinks is after the start time but it isnt

**Comment by fanerobinson** [comment]
same error

**Comment by huzzamo** [comment]
I think your referring to the pop-up notifications that say the time is in error triggers too fast.

This gets triggered on focus and onblur so you end up seeing 2 notifications for the same issue. These Toastr notifications do sometimes get triggered incorrectly as the fields allows diverse data types ie. 1p, 13, 1300,13.00 etc and just be overly cautious with time data. Let me know if it prevents saving a Post.

**Comment by fanerobinson** [comment]
im referring to no matter what i do, the start time will not change

**Comment by huzzamo** [comment]
Try now. Just do a hard refresh as updated the script file.

**Comment by fanerobinson** [comment]
yep now i can update time
