### ISSUE TITLE
search ticket doesnt work on open

### ISSUE THREAD

**Issue by fanerobinson** [fanerobinson/PSA#9]
it works on new but not open

**Comment by huzzamo** [comment]
Fixed.

**Comment by huzzamo** [comment]
You can search on ticket_description

![image](https://cloud.githubusercontent.com/assets/23496056/20515227/89be2380-b0cb-11e6-98ea-ef5126e7369e.png)

**Comment by huzzamo** [comment]
![image](https://cloud.githubusercontent.com/assets/23496056/20515238/9a640902-b0cb-11e6-9b78-de8f0b6828e0.png)

**Comment by fanerobinson** [comment]
good work, you can close when something is done mate
